### ISSUE TITLE
You have any images or video of how the code is running

### ISSUE THREAD

**Issue by HaseebWar** [kitimi88/dj-hyperbeam#1]

**Comment by kitimi88** [comment]
Hi there @HaseebWar ! Appreciate your feedback and apologies for late response due to holidays in my country. I’ve included some screenshots to the key features of this app and it should be viewable in the [readme](https://github.com/kitimi88/dj-hyperbeam#screenshots).  Also, I’ll try to come up with a video or gif as soon as I can. Thank you!
